### ISSUE TITLE
Can't install v2.0.1 with yarn 3

### ISSUE THREAD

**Issue by Perth27413** [es-shims/es-set-tostringtag#3]
I have using yarn 3 to install es-set-tostringtag v2.0.1
with command `yarn add es-set-tostringtag@2.0.1` and I got this message.
```
Error: es-set-tostringtag@npm:2.0.1: No candidates found
```

**Comment by Perth27413** [comment]
I'm so Sorry, My .yarnrc setting is invalid.

**Comment by ljharb** [comment]
In general, if you can’t install Y with X, it’s X’s fault, not Y’s :-)
